import chinafestImg from '/Users/kellygu/workspace/personal-portfolio/kelly-web/src/assets/images/chinafest.JPG';

export const csaPage = [
    { id: 1, title: "Chinafest", 
      img: chinafestImg,
    },
    { id: 2, title: "FullMoonFest", 
    img: chinafestImg,
},
    { id: 3, title: "Culturefest", 
      img: chinafestImg,
    },
    { id: 4, title: "Presidency", 
      img: chinafestImg,
    },
    { id: 5, title: "Presdiency2", 
      img: chinafestImg,
},
    { id: 6, title: "Presdiency3", 
      img: chinafestImg,
},  
];

export const akdphiPage = [
    { id: 1, title: "BCA Chair - Mr. Pink", 
      img: chinafestImg,
    },
    { id: 2, title: "BCA Chair - Volleyball Tournament", 
      img: chinafestImg,
    },
    { id: 3, title: "Historic Chair", 
      img: chinafestImg,
    },
    { id: 4, title: "Rush Chair", 
      img: chinafestImg,
    },
    { id: 5, title: "Reveals Chair", 
      img: chinafestImg,
    },
    { id: 6, title: "blah", 
      img: chinafestImg,
    },  
];
export const guzhengPage = [
    { id: 1, title: "Butterfly Lovers ft. Hana Wang", 
      img: chinafestImg,
    },
    { id: 2, title: "Li An Yi Hen ft. Cassi Chen", 
      img: chinafestImg,
    },
    { id: 3, title: "anotha one", 
      img: chinafestImg,
    },
    { id: 4, title: "one more", 
      img: chinafestImg,
    },
    { id: 5, title: "er", 
      img: chinafestImg,
    },
    { id: 6, title: "yer", 
      img: chinafestImg,
    },  
];
export const dancePage = [
    { id: 1, title: "Reminicence of the Breeze and Rain", 
      img: chinafestImg,
    },
    { id: 2, title: "Blooming Jasmine", 
      img: chinafestImg,
    },
    { id: 3, title: "Solo", 
      img: chinafestImg,
    },
    { id: 4, title: "anotha", 
      img: chinafestImg,
    },
    { id: 5, title: "anotha", 
      img: chinafestImg,
    },
    { id: 6, title: "anotha", 
      img: chinafestImg,
    },  
];
export const photographyPage = [
    { id: 1, title: "Fav Image", 
      img: chinafestImg,
    },
    { id: 2, title: "FaveImage2", 
      img: chinafestImg,
    },
    { id: 3, title: "FaveImage3", 
      img: chinafestImg,
    },
    { id: 4, title: "FaveImage4", 
      img: chinafestImg,
    },
    { id: 5, title: "FaveImage5", 
      img: chinafestImg,
    },
    { id: 6, title: "FaveImage6", 
      img: chinafestImg,
    },  
];
